// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhXwA2mAm6XmzWFv3zyjiftzyefyV9ow',
    appId: '1:952063960380:android:b395afbb1f88a605366a39',
    messagingSenderId: '952063960380',
    projectId: 'kaizen-5b90d',
    databaseURL: 'https://kaizen-5b90d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaizen-5b90d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzvPGI70nZHgSiXIYEHbP4WwaXhV35yE',
    appId: '1:952063960380:ios:2d080e3276b56faf366a39',
    messagingSenderId: '952063960380',
    projectId: 'kaizen-5b90d',
    databaseURL: 'https://kaizen-5b90d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kaizen-5b90d.appspot.com',
    iosClientId: '952063960380-fb5n5knfueuj6pqolerhrkd9alimlbe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.stolarczykApp',
  );
}
